"use client";

import { useEffect, type ReactNode } from "react";
import { useLocale } from "@/providers/locale-provider";
import type { PrintOrientation } from "@/types/print-engine";

/** Keeps the print tab on the light token set — a printed sheet is never theme-aware. */
function useForceLightTokens() {
  useEffect(() => {
    const root = document.documentElement;
    const wasDark = root.classList.contains("dark");
    const strip = () => {
      if (root.classList.contains("dark")) root.classList.remove("dark");
    };
    strip();
    root.style.colorScheme = "light";
    // next-themes may re-apply its class after this effect — keep stripping it.
    const observer = new MutationObserver(strip);
    observer.observe(root, { attributes: true, attributeFilter: ["class"] });
    return () => {
      observer.disconnect();
      root.style.colorScheme = "";
      if (wasDark) root.classList.add("dark");
    };
  }, []);
}

/**
 * The outer shell every print template renders through.
 *
 * - `@page` sets the physical A4 size/orientation and margins.
 * - Page numbers and the "generated by · printed at" line live in `@page`
 *   margin boxes (CSS Paged Media, Chrome/Edge 131+). That is the only place
 *   `counter(page)` / `counter(pages)` resolve reliably — a `position: fixed`
 *   footer always reads page 1 and overlaps content. The page number sits in
 *   the logical END corner (bottom-left in RTL, bottom-right in LTR).
 * - Colors come from the light design tokens (the print tab is forced light);
 *   the margin boxes use a fixed neutral ink (print-only exception) because
 *   the page context does not reliably inherit custom properties.
 * - Direction defaults to the UI language's direction.
 */
export function PrintPage({
  orientation,
  direction,
  printedAt,
  children,
}: {
  orientation: PrintOrientation;
  /** Explicit sheet direction; omitted → the active UI language's direction. */
  direction?: "rtl" | "ltr";
  /** Shown in the footer margin box of every sheet. */
  printedAt?: string;
  children: ReactNode;
}) {
  const { t, direction: uiDirection } = useLocale();
  useForceLightTokens();
  const dir = direction ?? uiDirection;
  // CSS `content` strings — JSON-escaped so a translation can never break the rule.
  const css = (value: string) => JSON.stringify(value);
  const pageCounter = `${css(`${t("reportExport.page")} `)} counter(page) ${css(` ${t("reportExport.of")} `)} counter(pages)`;
  const footerText = css(
    [t("reportExport.generatedBy"), printedAt ? `${t("reportExport.printedAt")} ${printedAt}` : ""]
      .filter(Boolean)
      .join("  ·  "),
  );
  const startBox = dir === "rtl" ? "bottom-right" : "bottom-left";
  const endBox = dir === "rtl" ? "bottom-left" : "bottom-right";
  const marginBox = `font-family: var(--font-sans), system-ui, sans-serif; font-size: 8pt; color: #475569; direction: ${dir};`;

  return (
    <div
      dir={dir}
      data-print-sheet
      className="min-h-screen bg-white p-[12mm] text-[11px] leading-normal text-foreground print:min-h-0 print:p-0"
    >
      {/* `@page` is document-scoped by spec — safe here because this route renders nothing else. */}
      <style>{`
        @page {
          size: A4 ${orientation};
          margin: 12mm 12mm 16mm;
          @${startBox} { content: ${footerText}; ${marginBox} }
          @${endBox} { content: ${pageCounter}; ${marginBox} }
        }
        html, body {
          background: #fff;
        }
        @media print {
          [data-print-sheet] {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          [data-print-sheet] thead {
            display: table-header-group;
          }
          [data-print-sheet] tr,
          [data-print-avoid-break] {
            break-inside: avoid;
          }
        }
      `}</style>
      {children}
    </div>
  );
}
