/**
 * Repeats on every printed sheet via `position: fixed` (a standard print
 * CSS technique — fixed-position elements re-render at the same physical
 * spot on each page). Page numbering uses the CSS Paged Media `@page`
 * counters declared in `PrintPage` — a progressive enhancement that
 * degrades to no text (never broken layout) in browsers without support.
 */
export function PrintFooter({
  printedAt,
  signatureLabel,
}: {
  printedAt: string;
  signatureLabel?: string;
}) {
  return (
    <footer className="fixed inset-x-0 bottom-0 flex items-end justify-between border-t border-slate-300 bg-white px-[12mm] py-2 text-[9px] text-slate-500">
      <span>Generated by OMS · Printed at {printedAt}</span>
      {signatureLabel && (
        <span className="border-t border-slate-400 px-8 pt-1 text-slate-600">{signatureLabel}</span>
      )}
      <span className="print-page-counter" />
    </footer>
  );
}
