"use client";

import { useEffect, type CSSProperties, type ReactNode } from "react";
import { Printer, X } from "lucide-react";
import { EnterpriseButton } from "@/components/ui/button";
import { useLocale } from "@/providers/locale-provider";
import type { PrintOrientation, PrintPaper } from "@/types/print-engine";

/** Keeps the print tab on the light token set — a printed sheet is never theme-aware. */
function useForceLightTokens() {
  useEffect(() => {
    const root = document.documentElement;
    const wasDark = root.classList.contains("dark");
    const strip = () => {
      if (root.classList.contains("dark")) root.classList.remove("dark");
    };
    strip();
    root.style.colorScheme = "light";
    // next-themes may re-apply its class after this effect — keep stripping it.
    const observer = new MutationObserver(strip);
    observer.observe(root, { attributes: true, attributeFilter: ["class"] });
    return () => {
      observer.disconnect();
      root.style.colorScheme = "";
      if (wasDark) root.classList.add("dark");
    };
  }, []);
}

/** Physical sheet (mm) and page margins per paper — print tokens, spec §2. */
const PAPER: Record<
  PrintPaper,
  { width: number; height: number; margin: [number, number, number]; footerPt: number }
> = {
  A4: { width: 210, height: 297, margin: [12, 12, 16], footerPt: 7.5 },
  A5: { width: 148, height: 210, margin: [8, 8, 10], footerPt: 6.5 },
};

/**
 * The outer shell every print template renders through.
 *
 * - `@page` sets the physical paper (A4 / A5), orientation and margins.
 * - Page numbers and the "generated by · printed at" line live in `@page`
 *   margin boxes (CSS Paged Media, Chrome/Edge 131+) — the only place
 *   `counter(page)` / `counter(pages)` resolve reliably. The page number sits
 *   in the logical END corner (bottom-left in RTL, bottom-right in LTR).
 * - On screen the sheet is drawn at its real paper width with the page
 *   margins as padding, under a toolbar with the print action and the printer
 *   settings a browser cannot enforce; the same DOM is what prints and what
 *   "Save as PDF" writes, so the preview is the output.
 * - Visual tokens: `theme/print.css` (`[data-print-sheet]`). The accent is the
 *   company brand color.
 */
export function PrintPage({
  orientation,
  paper = "A4",
  direction,
  printedAt,
  accentColor,
  showFooterLine = true,
  runningHeader,
  children,
}: {
  orientation: PrintOrientation;
  paper?: PrintPaper;
  /** Explicit sheet direction; omitted → the active UI language's direction. */
  direction?: "rtl" | "ltr";
  /** Shown in the footer margin box of every sheet. */
  printedAt?: string;
  /** Company brand color (`--pr-accent`). */
  accentColor?: string;
  /** Off for compact sheets (package slip) that print their own identity line. */
  showFooterLine?: boolean;
  /** Repeated at the top of every sheet (e.g. the order number on a multi-sheet slip). */
  runningHeader?: string;
  children: ReactNode;
}) {
  const { t, direction: uiDirection } = useLocale();
  useForceLightTokens();
  const dir = direction ?? uiDirection;
  const spec = PAPER[paper];
  const landscape = orientation === "landscape";
  const width = landscape ? spec.height : spec.width;
  const height = landscape ? spec.width : spec.height;
  const [top, side, bottom] = spec.margin;

  // CSS `content` strings — JSON-escaped so a translation can never break the rule.
  const css = (value: string) => JSON.stringify(value);
  const pageCounter = `${css(`${t("reportExport.page")} `)} counter(page) ${css(` ${t("reportExport.of")} `)} counter(pages)`;
  const footerText = css(
    [t("reportExport.generatedBy"), printedAt ? `${t("reportExport.printedAt")} ${printedAt}` : ""]
      .filter(Boolean)
      .join("  ·  "),
  );
  const startBox = dir === "rtl" ? "bottom-right" : "bottom-left";
  const endBox = dir === "rtl" ? "bottom-left" : "bottom-right";
  const topBox = dir === "rtl" ? "top-left" : "top-right";
  // Margin boxes do not inherit custom properties reliably — fixed neutral ink.
  const marginBox = `font-family: var(--font-sans), system-ui, sans-serif; font-size: ${spec.footerPt}pt; color: #4d4d4d; direction: ${dir};`;

  const paperLabel = t(
    paper === "A5"
      ? "printDocument.paperA5Portrait"
      : landscape
        ? "printDocument.paperA4Landscape"
        : "printDocument.paperA4Portrait",
  );
  const hint =
    paper === "A5" ? t("printDocument.hintA5") : t("printDocument.hintA4", { paper: paperLabel });

  const print = () => {
    document.fonts.ready.then(() => window.print()).catch(() => window.print());
  };

  return (
    <div
      dir={dir}
      data-print-sheet
      data-paper={paper}
      data-orientation={orientation}
      style={accentColor ? ({ "--pr-brand": accentColor } as CSSProperties) : undefined}
    >
      {/* `@page` is document-scoped by spec — safe here because this route renders nothing else. */}
      <style>{`
        @page {
          size: ${paper} ${orientation};
          margin: ${top}mm ${side}mm ${bottom}mm;
          @${startBox} { content: ${showFooterLine ? footerText : '""'}; ${marginBox} }
          @${endBox} { content: ${pageCounter}; ${marginBox} }
          ${runningHeader ? `@${topBox} { content: ${css(runningHeader)}; ${marginBox} font-weight: 600; }` : ""}
        }
        html, body { background: #fff; }
      `}</style>
      <div className="pr-toolbar" role="toolbar" aria-label={t("printDocument.toolbarPrint")}>
        <EnterpriseButton type="button" onClick={print} data-testid="print-now">
          <Printer />
          {t("printDocument.toolbarPrint")}
        </EnterpriseButton>
        <EnterpriseButton type="button" variant="ghost" onClick={() => window.close()}>
          <X />
          {t("printDocument.toolbarClose")}
        </EnterpriseButton>
        <span className="pr-toolbar-paper" data-testid="print-paper">
          {paperLabel}
        </span>
        <span className="pr-toolbar-hint">{hint}</span>
      </div>
      <div className="pr-desk">
        <div
          className="pr-sheet"
          style={{
            width: `${width}mm`,
            minHeight: `${height}mm`,
            padding: `${top}mm ${side}mm ${bottom}mm`,
          }}
        >
          {children}
        </div>
      </div>
    </div>
  );
}
