"use client";

import { Printer } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import {
  EnterpriseCard,
  EnterpriseCardContent,
  EnterpriseCardHeader,
  EnterpriseCardTitle,
} from "@/components/ui/card";
import { EnterpriseButton } from "@/components/ui/button";
import { EnterpriseBadge } from "@/components/ui/badge";
import { usePrintEngine } from "@/hooks/use-print-engine";
import { useCompany } from "@/providers/company-provider";
import { useUserContext } from "@/providers/user-context";
import type { DocumentData, DocumentType } from "@/types/document-engine";
import { useLocale } from "@/providers/locale-provider";

const DOCUMENT_TYPES: DocumentType[] = [
  "quotation",
  "sales-order",
  "tax-invoice",
  "simplified-invoice",
  "purchase-order",
  "purchase-request",
  "customer-statement",
  "supplier-statement",
  "receipt-voucher",
  "payment-voucher",
  "journal-voucher",
  "inventory-transfer",
  "delivery-note",
  "packing-list",
  "picking-list",
];

export default function DocumentPreviewPage() {
  const { t, direction } = useLocale();
  const { printDocument } = usePrintEngine();
  const { activeCompany } = useCompany();
  const { user } = useUserContext();

  const sampleData: DocumentData = {
    type: "quotation",
    documentNumber: "QT-2026-0142",
    documentDate: "2026-07-30",
    currency: "SAR",
    company: {
      name: activeCompany?.name ?? "Acme Trading",
      taxNumber: "310123456700003",
      addressLines: ["King Fahd Road", "Riyadh, Saudi Arabia"],
      branding: {
        logoUrl: activeCompany?.logoUrl ?? null,
        primaryColor: activeCompany?.primaryColor ?? "#0F8A5F",
        secondaryColor: activeCompany?.secondaryColor ?? "#2563EB",
        footerText: "Sample document, generated by the Document Engine foundation.",
        paperSize: "a4-portrait",
        language: direction === "rtl" ? "rtl" : "ltr",
      },
    },
    party: {
      name: "Sample Customer Ltd.",
      taxNumber: "300987654300003",
      addressLines: ["Al Olaya District", "Riyadh, Saudi Arabia"],
    },
    meta: [{ label: t("documentEngine.validUntil"), value: "2026-08-30" }],
    lineItems: [
      {
        id: "1",
        description: "Sample Product A",
        quantity: 10,
        unit: "pcs",
        unitPrice: 120,
        total: 1200,
      },
      {
        id: "2",
        description: "Sample Product B",
        quantity: 5,
        unit: "pcs",
        unitPrice: 340,
        total: 1700,
      },
    ],
    totals: [
      { label: t("documentEngine.subtotal"), value: 2900 },
      { label: t("documentEngine.tax"), value: 435 },
      { label: t("documentEngine.total"), value: 3335, emphasis: true },
    ],
    notes:
      "This is a sample document proving the shared Document Engine layout — not a real quotation.",
    signatures: [
      { label: t("documentEngine.signaturePreparedBy") },
      { label: t("documentEngine.signatureCustomer") },
    ],
  };

  const handlePrint = () => {
    printDocument({
      variant: "invoice",
      title: t("documentEngine.quotationTitle"),
      printedByName: user?.fullName ?? null,
      data: sampleData,
      labels: {
        documentNumber: t("documentEngine.documentNumber"),
        documentDate: t("documentEngine.documentDate"),
        billTo: t("documentEngine.billTo"),
        description: t("documentEngine.description"),
        quantity: t("documentEngine.quantity"),
        unitPrice: t("documentEngine.unitPrice"),
        lineTotal: t("documentEngine.lineTotal"),
        notes: t("documentEngine.notes"),
      },
    });
  };

  return (
    <div className="flex flex-col gap-8 pb-16">
      <PageHeader title={t("documentEngine.title")} subtitle={t("documentEngine.subtitle")} />

      <div className="grid gap-4 lg:grid-cols-3">
        <EnterpriseCard>
          <EnterpriseCardHeader>
            <EnterpriseCardTitle>{t("documentEngine.supportedTypesTitle")}</EnterpriseCardTitle>
          </EnterpriseCardHeader>
          <EnterpriseCardContent className="flex flex-wrap gap-1.5">
            {DOCUMENT_TYPES.map((docType) => (
              <EnterpriseBadge key={docType} variant="secondary" className="font-normal">
                {docType}
              </EnterpriseBadge>
            ))}
          </EnterpriseCardContent>
        </EnterpriseCard>
        <EnterpriseCard>
          <EnterpriseCardHeader>
            <EnterpriseCardTitle>{t("documentEngine.printSettingsTitle")}</EnterpriseCardTitle>
          </EnterpriseCardHeader>
          <EnterpriseCardContent>
            <p className="text-body text-muted-foreground">
              {t("documentEngine.printSettingsBody")}
            </p>
          </EnterpriseCardContent>
        </EnterpriseCard>
        <EnterpriseCard>
          <EnterpriseCardHeader>
            <EnterpriseCardTitle>{t("documentEngine.brandingTitle")}</EnterpriseCardTitle>
          </EnterpriseCardHeader>
          <EnterpriseCardContent>
            <p className="text-body text-muted-foreground">{t("documentEngine.brandingBody")}</p>
          </EnterpriseCardContent>
        </EnterpriseCard>
      </div>

      <section className="flex flex-col gap-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-section-title">{t("documentEngine.previewHeading")}</h2>
        </div>

        <EnterpriseCard>
          <EnterpriseCardContent className="flex flex-col items-start gap-3 py-8">
            <p className="text-body text-muted-foreground">{t("documentEngine.printEngineBody")}</p>
            <EnterpriseButton type="button" onClick={handlePrint}>
              <Printer />
              {t("documentEngine.printPreview")}
            </EnterpriseButton>
          </EnterpriseCardContent>
        </EnterpriseCard>
      </section>
    </div>
  );
}
