import {
  Body,
  Controller,
  HttpCode,
  Param,
  Post,
  UseGuards,
} from '@nestjs/common';
import { JwtAuthGuard } from '../../auth/guards/jwt-auth.guard';
import { CurrentUser } from '../../auth/decorators/current-user.decorator';
import type { JwtPayload } from '../../auth/guards/jwt-auth.guard';
import { AccountingPeriodsService } from './accounting-periods.service';
import { BulkPeriodActionDto } from './dto/bulk-period-action.dto';

/** Business operations only: Close, Reopen, Lock, Unlock, Bulk Close, Bulk Open. Periods are never created/edited/deleted directly — they're generated by FiscalYearsService.create(). */
@Controller('accounting/periods')
@UseGuards(JwtAuthGuard)
export class AccountingPeriodsController {
  constructor(private readonly periods: AccountingPeriodsService) {}

  @Post(':id/close')
  @HttpCode(200)
  close(@Param('id') id: string, @CurrentUser() user: JwtPayload) {
    return this.periods.close(id, user.sub);
  }

  @Post(':id/reopen')
  @HttpCode(200)
  reopen(@Param('id') id: string, @CurrentUser() user: JwtPayload) {
    return this.periods.reopen(id, user.sub);
  }

  @Post(':id/lock')
  @HttpCode(200)
  lock(@Param('id') id: string, @CurrentUser() user: JwtPayload) {
    return this.periods.lock(id, user.sub);
  }

  @Post(':id/unlock')
  @HttpCode(200)
  unlock(@Param('id') id: string, @CurrentUser() user: JwtPayload) {
    return this.periods.unlock(id, user.sub);
  }

  @Post('bulk-close')
  @HttpCode(200)
  bulkClose(@Body() dto: BulkPeriodActionDto, @CurrentUser() user: JwtPayload) {
    return this.periods.bulkClose(dto.ids, user.sub);
  }

  @Post('bulk-open')
  @HttpCode(200)
  bulkOpen(@Body() dto: BulkPeriodActionDto, @CurrentUser() user: JwtPayload) {
    return this.periods.bulkOpen(dto.ids, user.sub);
  }
}
