-- Sequences backing Supplier.supplierNumber ("SUP-000001", ...) and
-- PurchaseOrder.poNumber ("PO-000001", ...). Independent from every other
-- number sequence in this codebase. Generated by the application
-- (SuppliersService / PurchaseOrdersService), not a Prisma-managed default,
-- so neither is declared in schema.prisma.
CREATE SEQUENCE IF NOT EXISTS supplier_number_seq;
CREATE SEQUENCE IF NOT EXISTS purchase_order_number_seq;
