-- Sequence backing InventoryMovement.movementNumber ("MV-000001", ...).
-- Independent from lead_number_seq / sales_order_number_seq /
-- payment_number_seq. Generated by the application (InventoryService), not a
-- Prisma-managed default, so it isn't declared in schema.prisma.
CREATE SEQUENCE IF NOT EXISTS inventory_movement_number_seq;
