import {
  LayoutDashboard,
  Users,
  UserCog,
  KeyRound,
  ShieldCheck,
  ShoppingCart,
  Receipt,
  Package,
  Ruler,
  Tags,
  Boxes,
  Warehouse,
  Truck,
  ShoppingBag,
  Calculator,
  Wallet,
  Landmark,
  CreditCard,
  Settings,
  Globe,
  Coins,
  ClipboardList,
  Building2,
  FolderKanban,
  Contact,
  ArrowLeftRight,
  Layers,
  Award,
  FileText,
  Banknote,
  Ship,
  GitBranch,
  Percent,
  UsersRound,
  MapPin,
  Languages,
  BarChart3,
  Database,
  Hash,
  Library,
  CalendarCheck2,
  Printer,
  Plug,
  Bell,
  Shield,
  HardDrive,
  SlidersHorizontal,
  CalendarClock,
  Undo2,
  BookText,
  Target,
  UploadCloud,
} from "lucide-react";

/**
 * String -> component lookup so `navigation.config.ts` can stay pure,
 * serializable data (`icon: "package"`) instead of importing JSX. Add new
 * icons here as new modules are added to the config.
 */
export const iconRegistry = {
  dashboard: LayoutDashboard,
  users: Users,
  "user-cog": UserCog,
  "key-round": KeyRound,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  receipt: Receipt,
  package: Package,
  ruler: Ruler,
  tags: Tags,
  boxes: Boxes,
  warehouse: Warehouse,
  truck: Truck,
  "shopping-bag": ShoppingBag,
  calculator: Calculator,
  wallet: Wallet,
  landmark: Landmark,
  "credit-card": CreditCard,
  settings: Settings,
  globe: Globe,
  coins: Coins,
  "clipboard-list": ClipboardList,
  building: Building2,
  "folder-kanban": FolderKanban,
  contact: Contact,
  "arrow-left-right": ArrowLeftRight,
  layers: Layers,
  award: Award,
  "file-text": FileText,
  banknote: Banknote,
  ship: Ship,
  "git-branch": GitBranch,
  percent: Percent,
  "users-round": UsersRound,
  "map-pin": MapPin,
  languages: Languages,
  "bar-chart": BarChart3,
  database: Database,
  hash: Hash,
  printer: Printer,
  plug: Plug,
  bell: Bell,
  shield: Shield,
  "hard-drive": HardDrive,
  sliders: SlidersHorizontal,
  "calendar-clock": CalendarClock,
  "undo-2": Undo2,
  "book-text": BookText,
  target: Target,
  library: Library,
  "calendar-check": CalendarCheck2,
  "upload-cloud": UploadCloud,
} as const;

export type IconName = keyof typeof iconRegistry;
