import type { NavigationItem } from "../types/navigation";

/**
 * Single source of truth for the entire OMS sidebar. Authored as a FLAT
 * list — every item declares its own `parent` id — so adding a future
 * module only ever means appending one entry here, never editing a nested
 * array or a layout component. `buildNavigationTree` (see
 * `build-navigation-tree.ts`) assembles the flat list into the nested
 * `children` structure the Sidebar actually renders.
 *
 * `titleKey`/`subtitleKey` are i18n message keys (see `src/i18n`), resolved
 * at render time via `useLocale().t()` — never literal display text, since
 * Arabic is the default locale and English is a future secondary one.
 *
 * Sidebar is organized by business ownership (Sales, Shipping, Purchasing,
 * Products & Warehouses, Finance, Data Management), not by database/master-
 * data classification. Shipping Statuses / Methods / Companies live under
 * Shipping — never under Products or generic Basic Data. Customer Groups
 * stay under Sales (distinct from Customers); Supplier Groups stay under
 * Purchasing (distinct from Suppliers). The Products parent has no
 * permission gate so inventory-only users still see movements/stock/count
 * without being granted `products.view`. Identity & Permissions no longer
 * exists as a top-level module.
 * TASK-060 — Roles/RBAC no longer exists (permissions are granted directly
 * per-user from the User Editor); `settings-roles`/`settings-permissions`
 * were removed accordingly, no standalone Permissions page.
 *
 * Routes with no page built yet will 404 until their business pages ship in
 * a later phase — that is expected, not a bug.
 */
export const navigationConfig: NavigationItem[] = [
  {
    id: "dashboard",
    titleKey: "nav.dashboard",
    subtitleKey: "nav.dashboardSubtitle",
    icon: "dashboard",
    route: "/",
    order: 0,
  },

  { id: "crm", titleKey: "nav.crm", icon: "users", order: 10, permissions: ["crm.view"] },
  {
    id: "crm-leads",
    titleKey: "nav.crmLeads",
    parent: "crm",
    route: "/crm/leads",
    icon: "contact",
    order: 0,
    permissions: ["crm.leads.view"],
  },
  {
    id: "crm-funnel",
    titleKey: "workflow.funnel.title",
    parent: "crm",
    route: "/crm/funnel",
    icon: "bar-chart",
    order: 1,
    permissions: ["crm.leads.view"],
  },

  {
    id: "sales",
    titleKey: "nav.sales",
    icon: "shopping-cart",
    order: 20,
    permissions: ["sales.view"],
  },
  {
    id: "sales-customers",
    titleKey: "nav.salesCustomers",
    parent: "sales",
    route: "/sales/customers",
    icon: "contact",
    order: 0,
    permissions: ["partners.view"],
  },
  {
    id: "master-data-customer-groups",
    titleKey: "masterData.customerGroups.title",
    parent: "sales",
    route: "/master-data/customer-groups",
    icon: "users-round",
    order: 1,
    permissions: ["partners.view"],
  },
  {
    id: "sales-quotations",
    titleKey: "nav.salesQuotations",
    parent: "sales",
    route: "/sales/quotations",
    icon: "file-text",
    order: 2,
    permissions: ["sales.quotations.view"],
  },
  {
    id: "sales-orders",
    titleKey: "nav.salesOrders",
    parent: "sales",
    route: "/sales/orders",
    icon: "shopping-cart",
    order: 3,
    permissions: ["sales.orders.view"],
  },
  {
    id: "store-orders-list",
    titleKey: "nav.storeOrdersList",
    parent: "sales",
    route: "/store-orders",
    icon: "store",
    order: 4,
    permissions: ["store-orders.view"],
  },
  {
    id: "store-orders-import",
    titleKey: "nav.storeOrdersImport",
    parent: "sales",
    route: "/store-orders/import",
    icon: "upload-cloud",
    order: 5,
    permissions: ["store-orders.view"],
  },
  {
    id: "store-orders-needs-review",
    titleKey: "nav.storeOrdersNeedsReview",
    parent: "sales",
    route: "/store-orders/needs-review",
    icon: "list-checks",
    order: 6,
    permissions: ["store-orders.view"],
  },
  {
    id: "sales-invoices",
    titleKey: "nav.salesInvoices",
    parent: "sales",
    route: "/sales/invoices",
    icon: "receipt",
    order: 7,
    permissions: ["sales.invoices.view"],
  },
  {
    id: "sales-returns",
    titleKey: "nav.salesReturns",
    parent: "sales",
    route: "/sales/returns",
    icon: "undo-2",
    order: 8,
    permissions: ["sales.returns.view"],
  },
  /// Dedicated Shipping module — operational desk plus the shipping master
  /// data that belongs to it (statuses, methods, companies). Those screens
  /// must not appear under Products or Basic Data.
  {
    id: "shipping",
    titleKey: "nav.shipping",
    icon: "ship",
    order: 25,
    permissions: ["shipping.view"],
  },
  {
    id: "store-orders-shipping",
    titleKey: "nav.storeOrdersShipping",
    parent: "shipping",
    route: "/shipping",
    icon: "ship",
    order: 0,
    permissions: ["shipping.view"],
  },
  {
    id: "store-orders-shipping-import",
    titleKey: "nav.storeOrdersShippingImport",
    parent: "shipping",
    route: "/shipping/import",
    icon: "upload-cloud",
    order: 1,
    permissions: ["shipping.view"],
  },
  {
    id: "master-data-shipping-statuses",
    titleKey: "masterData.shippingStatuses.title",
    parent: "shipping",
    route: "/master-data/shipping-statuses",
    icon: "list-checks",
    order: 2,
    permissions: ["shipping.view"],
  },
  {
    id: "master-data-workflow-statuses",
    titleKey: "masterData.workflowStatuses.title",
    parent: "master-data",
    route: "/master-data/workflow-statuses",
    icon: "list-checks",
    order: 25,
    permissions: ["masterdata.view"],
  },
  {
    id: "master-data-workflow-transitions",
    titleKey: "workflow.transitions.title",
    parent: "master-data",
    route: "/master-data/workflow-transitions",
    icon: "git-branch",
    order: 26,
    permissions: ["masterdata.view"],
  },
  {
    id: "master-data-shipping-companies",
    titleKey: "masterData.shippingCompanies.title",
    parent: "shipping",
    route: "/master-data/shipping-companies",
    icon: "truck",
    order: 3,
    permissions: ["shipping.view"],
  },

  {
    id: "purchasing",
    titleKey: "nav.purchasing",
    icon: "shopping-bag",
    order: 30,
    permissions: ["purchasing.view"],
  },
  {
    id: "purchasing-suppliers",
    titleKey: "nav.purchasingSuppliers",
    parent: "purchasing",
    route: "/purchasing/suppliers",
    icon: "truck",
    order: 0,
    permissions: ["partners.view"],
  },
  {
    id: "master-data-supplier-groups",
    titleKey: "masterData.supplierGroups.title",
    parent: "purchasing",
    route: "/master-data/supplier-groups",
    icon: "users-round",
    order: 1,
    permissions: ["partners.view"],
  },
  {
    id: "purchasing-quotations",
    titleKey: "nav.purchasingQuotations",
    parent: "purchasing",
    route: "/purchasing/purchase-quotations",
    icon: "file-text",
    order: 2,
    permissions: ["purchasing.quotations.view"],
  },
  {
    id: "purchasing-orders",
    titleKey: "nav.purchasingOrders",
    parent: "purchasing",
    route: "/purchasing/purchase-orders",
    icon: "clipboard-list",
    order: 3,
    permissions: ["purchasing.orders.view"],
  },
  {
    id: "purchasing-invoices",
    titleKey: "nav.purchasingInvoices",
    parent: "purchasing",
    route: "/purchasing/purchase-invoices",
    icon: "receipt",
    order: 4,
    permissions: ["purchasing.invoices.view"],
  },
  {
    id: "purchasing-returns",
    titleKey: "nav.purchasingReturns",
    parent: "purchasing",
    route: "/purchasing/purchase-returns",
    icon: "undo-2",
    order: 5,
    permissions: ["purchasing.returns.view"],
  },
  {
    id: "products",
    titleKey: "nav.products",
    icon: "package",
    order: 40,
  },
  {
    id: "products-list",
    titleKey: "nav.productsList",
    parent: "products",
    route: "/products",
    icon: "package",
    order: 0,
    permissions: ["products.view"],
  },
  {
    id: "master-data-warehouses",
    titleKey: "masterData.warehouses.title",
    parent: "products",
    route: "/master-data/warehouses",
    icon: "warehouse",
    order: 1,
    permissions: ["products.view"],
  },
  {
    id: "master-data-warehouse-locations",
    titleKey: "masterData.warehouseLocations.title",
    parent: "products",
    route: "/master-data/warehouse-locations",
    icon: "map-pin",
    order: 2,
    permissions: ["products.view"],
  },
  {
    id: "master-data-units",
    titleKey: "masterData.units.title",
    parent: "products",
    route: "/master-data/units",
    icon: "ruler",
    order: 3,
    permissions: ["products.view"],
  },
  {
    id: "master-data-unit-conversions",
    titleKey: "masterData.unitConversions.title",
    parent: "products",
    route: "/master-data/unit-conversions",
    icon: "arrow-left-right",
    order: 4,
    permissions: ["products.view"],
  },
  {
    id: "master-data-categories",
    titleKey: "masterData.categories.title",
    parent: "products",
    route: "/master-data/categories",
    icon: "tags",
    order: 5,
    permissions: ["products.view"],
  },
  {
    id: "master-data-brands",
    titleKey: "masterData.brands.title",
    parent: "products",
    route: "/master-data/brands",
    icon: "award",
    order: 6,
    permissions: ["products.view"],
  },
  {
    id: "inventory-movements",
    titleKey: "nav.inventoryMovements",
    parent: "products",
    route: "/inventory/movements",
    icon: "arrow-left-right",
    order: 7,
    permissions: ["inventory.view"],
  },
  {
    id: "inventory-stock",
    titleKey: "nav.inventoryStock",
    parent: "products",
    route: "/inventory/stock",
    icon: "layers",
    order: 8,
    permissions: ["inventory.view"],
  },
  {
    id: "inventory-physical-count",
    titleKey: "nav.inventoryPhysicalCount",
    parent: "products",
    route: "/inventory/physical-count",
    icon: "clipboard-list",
    order: 9,
    permissions: ["inventory.view"],
  },

  {
    id: "expenses",
    titleKey: "nav.expenses",
    icon: "calculator",
    order: 60,
    permissions: ["expenses.view"],
  },
  {
    id: "expenses-components",
    titleKey: "nav.expensesComponents",
    parent: "expenses",
    route: "/expenses/cost-components",
    icon: "calculator",
    order: 0,
  },
  {
    id: "expenses-product-cost",
    titleKey: "nav.expensesProductCost",
    parent: "expenses",
    route: "/expenses/product-cost",
    icon: "file-text",
    order: 1,
  },

  {
    id: "finance",
    titleKey: "nav.finance",
    icon: "landmark",
    order: 70,
    permissions: ["finance.view"],
  },
  {
    id: "finance-receiving-accounts",
    titleKey: "nav.financeReceivingAccounts",
    parent: "finance",
    route: "/finance/receiving-accounts",
    icon: "landmark",
    order: 0,
  },
  {
    id: "finance-journal-entries",
    titleKey: "nav.financeJournalEntries",
    parent: "finance",
    route: "/finance/journal-entries",
    icon: "book-text",
    order: 1,
    permissions: ["accounting.journal-entries.view"],
  },
  {
    id: "finance-chart-of-accounts",
    titleKey: "nav.financeChartOfAccounts",
    parent: "finance",
    route: "/finance/chart-of-accounts",
    icon: "file-text",
    order: 2,
    permissions: ["accounting.chart-of-accounts.view"],
  },
  {
    id: "finance-cost-centers",
    titleKey: "nav.financeCostCenters",
    parent: "finance",
    route: "/finance/cost-centers",
    icon: "target",
    order: 3,
  },
  {
    id: "master-data-analytic-accounts",
    titleKey: "masterData.analyticAccounts.title",
    parent: "finance",
    route: "/master-data/analytic-accounts",
    icon: "git-branch",
    order: 4,
  },
  {
    id: "master-data-analytic-plans",
    titleKey: "masterData.analyticPlans.title",
    parent: "finance",
    route: "/master-data/analytic-plans",
    icon: "folder-kanban",
    order: 5,
  },
  {
    id: "master-data-payment-methods",
    titleKey: "masterData.paymentMethods.title",
    parent: "finance",
    route: "/master-data/payment-methods",
    icon: "banknote",
    order: 6,
  },
  {
    id: "master-data-payment-terms",
    titleKey: "masterData.paymentTerms.title",
    parent: "finance",
    route: "/master-data/payment-terms",
    icon: "calendar-clock",
    order: 7,
  },
  {
    id: "finance-expenses",
    titleKey: "nav.financeExpenses",
    parent: "finance",
    route: "/finance/expenses",
    icon: "receipt",
    order: 8,
  },
  {
    id: "finance-customer-receipts",
    titleKey: "nav.financeCustomerReceipts",
    parent: "finance",
    route: "/sales/payments",
    icon: "banknote",
    order: 9,
    permissions: ["sales.receipts.view"],
  },
  {
    id: "finance-supplier-payments",
    titleKey: "nav.financeSupplierPayments",
    parent: "finance",
    route: "/purchasing/payments",
    icon: "wallet",
    order: 10,
    permissions: ["purchasing.payments.view"],
  },
  {
    id: "finance-bank-transactions",
    titleKey: "nav.financeBankTransactions",
    parent: "finance",
    route: "/finance/bank-transactions",
    icon: "landmark",
    order: 11,
    permissions: ["accounting.bank-transactions.view"],
  },
  {
    id: "finance-journals",
    titleKey: "nav.financeJournals",
    parent: "finance",
    route: "/finance/journals",
    icon: "library",
    order: 12,
  },
  {
    id: "finance-payment-sources",
    titleKey: "nav.financePaymentSources",
    parent: "finance",
    route: "/finance/payment-sources",
    icon: "credit-card",
    order: 13,
  },
  {
    id: "finance-projects",
    titleKey: "nav.financeProjects",
    parent: "finance",
    route: "/finance/projects",
    icon: "folder-kanban",
    order: 14,
  },
  {
    id: "finance-fixed-assets",
    titleKey: "nav.financeFixedAssets",
    parent: "finance",
    route: "/finance/fixed-assets",
    icon: "building",
    order: 15,
  },
  {
    id: "finance-fiscal-periods",
    titleKey: "nav.financeFiscalPeriods",
    parent: "finance",
    route: "/finance/fiscal-periods",
    icon: "calendar-clock",
    order: 16,
  },
  {
    id: "finance-opening-balances",
    titleKey: "nav.financeOpeningBalances",
    parent: "finance",
    route: "/finance/opening-balances",
    icon: "wallet",
    order: 17,
    permissions: ["accounting.opening-balances.view"],
  },
  {
    id: "finance-year-closing",
    titleKey: "nav.financeYearClosing",
    parent: "finance",
    route: "/finance/year-closing",
    icon: "calendar-check",
    order: 18,
  },
  {
    id: "finance-accounting-settings",
    titleKey: "nav.financeAccountingSettings",
    parent: "finance",
    route: "/finance/accounting-settings",
    icon: "sliders",
    order: 19,
  },
  {
    id: "master-data-currencies",
    titleKey: "masterData.currencies.title",
    parent: "finance",
    route: "/master-data/currencies",
    icon: "coins",
    order: 20,
  },
  {
    id: "master-data-taxes",
    titleKey: "masterData.taxes.title",
    parent: "finance",
    route: "/master-data/taxes",
    icon: "percent",
    order: 21,
  },

  /// Standalone top-level module (Enterprise Import Center) — a single
  /// centralized entry point for Excel/CSV/Google Sheets imports across
  /// every module, deliberately not nested under Finance since it also
  /// covers Sales/Purchasing/Inventory/CRM data.
  {
    id: "data-management",
    titleKey: "nav.dataManagement",
    icon: "layers",
    order: 85,
    permissions: ["datamanagement.view"],
  },
  {
    id: "data-management-import-center",
    titleKey: "nav.dataManagementImportCenter",
    parent: "data-management",
    route: "/data-management/import-center",
    icon: "upload-cloud",
    order: 0,
    permissions: ["import-center.view"],
  },

  /// Cross-cutting geographic/language reference data that does not belong
  /// to a single operational module. Domain master data (warehouses,
  /// payment methods, customer groups, …) lives under its owning section.
  {
    id: "master-data",
    titleKey: "nav.masterData",
    icon: "database",
    order: 80,
    permissions: ["masterdata.view"],
  },
  {
    id: "master-data-countries",
    titleKey: "masterData.countries.title",
    parent: "master-data",
    route: "/master-data/countries",
    icon: "globe",
    order: 0,
  },
  {
    id: "master-data-cities",
    titleKey: "masterData.cities.title",
    parent: "master-data",
    route: "/master-data/cities",
    icon: "map-pin",
    order: 1,
  },
  {
    id: "master-data-languages",
    titleKey: "masterData.languages.title",
    parent: "master-data",
    route: "/master-data/languages",
    icon: "languages",
    order: 2,
  },
  {
    id: "master-data-transaction-types",
    titleKey: "masterData.transactionTypes.title",
    parent: "master-data",
    route: "/master-data/transaction-types",
    icon: "arrow-left-right",
    order: 3,
  },

  /// Core module (must always exist) — shell only, no report is generated
  /// yet (TASK-024 Part 5). Categories are direct children, same shape as
  /// Master Data above.
  {
    id: "reports",
    titleKey: "nav.reports",
    icon: "bar-chart",
    order: 90,
    permissions: ["reports.view"],
  },
  {
    id: "reports-executive",
    titleKey: "nav.reportsExecutive",
    parent: "reports",
    route: "/reports/executive",
    icon: "bar-chart",
    order: 0,
  },
  {
    id: "reports-sales",
    titleKey: "nav.reportsSales",
    parent: "reports",
    route: "/reports/sales",
    icon: "shopping-cart",
    order: 1,
  },
  {
    id: "reports-crm",
    titleKey: "nav.reportsCrm",
    parent: "reports",
    route: "/reports/crm",
    icon: "contact",
    order: 2,
  },
  {
    id: "reports-purchasing",
    titleKey: "nav.reportsPurchasing",
    parent: "reports",
    route: "/reports/purchasing",
    icon: "shopping-bag",
    order: 3,
  },
  {
    id: "reports-inventory",
    titleKey: "nav.reportsInventory",
    parent: "reports",
    route: "/reports/inventory",
    icon: "boxes",
    order: 4,
    permissions: ["reports.inventory.view"],
  },
  {
    id: "reports-finance",
    titleKey: "nav.reportsFinance",
    parent: "reports",
    route: "/reports/finance",
    icon: "landmark",
    order: 5,
    permissions: ["reports.financial.view"],
  },
  {
    id: "reports-expenses",
    titleKey: "nav.reportsExpenses",
    parent: "reports",
    route: "/reports/expenses",
    icon: "calculator",
    order: 6,
  },
  {
    id: "reports-customers",
    titleKey: "nav.reportsCustomers",
    parent: "reports",
    route: "/reports/customers",
    icon: "users-round",
    order: 7,
  },
  {
    id: "reports-suppliers",
    titleKey: "nav.reportsSuppliers",
    parent: "reports",
    route: "/reports/suppliers",
    icon: "truck",
    order: 8,
  },
  {
    id: "reports-shipping",
    titleKey: "nav.reportsShipping",
    parent: "reports",
    route: "/reports/shipping",
    icon: "ship",
    order: 9,
  },
  {
    id: "reports-custom",
    titleKey: "nav.reportsCustom",
    parent: "reports",
    route: "/reports/custom",
    icon: "file-text",
    order: 10,
  },
  {
    id: "reports-analytics",
    titleKey: "nav.reportsAnalytics",
    parent: "reports",
    route: "/reports/analytics",
    icon: "layers",
    order: 11,
  },

  /// System configuration ONLY (TASK-024 Part 4) — no master data lives
  /// here. Every child is a shell page: "Prepare pages only."
  {
    id: "settings",
    titleKey: "nav.settings",
    icon: "settings",
    order: 100,
    permissions: ["settings.view"],
  },
  {
    id: "settings-general",
    titleKey: "nav.settingsGeneral",
    parent: "settings",
    route: "/settings/general",
    icon: "sliders",
    order: 0,
  },
  {
    id: "settings-users",
    titleKey: "nav.settingsUsers",
    parent: "settings",
    route: "/settings/users",
    icon: "users",
    order: 1,
    permissions: ["settings.manage"],
  },
  {
    id: "settings-document-numbering",
    titleKey: "nav.settingsDocumentNumbering",
    parent: "settings",
    route: "/settings/document-numbering",
    icon: "hash",
    order: 4,
  },
  {
    id: "settings-print-settings",
    titleKey: "nav.settingsPrintSettings",
    parent: "settings",
    route: "/settings/print-settings",
    icon: "printer",
    order: 5,
  },
  {
    id: "settings-notifications",
    titleKey: "nav.settingsNotifications",
    parent: "settings",
    route: "/settings/notifications",
    icon: "bell",
    order: 6,
  },
  {
    id: "settings-integrations",
    titleKey: "nav.settingsIntegrations",
    parent: "settings",
    route: "/settings/integrations",
    icon: "plug",
    order: 7,
  },
  {
    id: "settings-security",
    titleKey: "nav.settingsSecurity",
    parent: "settings",
    route: "/settings/security",
    icon: "shield",
    order: 8,
  },
  {
    id: "settings-backup",
    titleKey: "nav.settingsBackup",
    parent: "settings",
    route: "/settings/backup",
    icon: "hard-drive",
    order: 9,
  },
];
