import type { NavigationGroupId, NavigationItem } from "../types/navigation";
import type { MessageKey } from "../i18n/translate";

/**
 * Sub-groups for large sections — rendered as quiet headings inside the
 * expanded section so 30+ links read as a few scannable clusters.
 */
export const NAVIGATION_GROUPS: Record<NavigationGroupId, { titleKey: MessageKey; order: number }> =
  {
    "finance-operations": { titleKey: "sidebar.groups.financeOperations", order: 0 },
    "finance-ledger": { titleKey: "sidebar.groups.financeLedger", order: 1 },
    "finance-assets": { titleKey: "sidebar.groups.financeAssets", order: 2 },
    "finance-setup": { titleKey: "sidebar.groups.financeSetup", order: 3 },
  };

/**
 * Single source of truth for the entire OMS sidebar. Authored as a FLAT
 * list — every item declares its own `parent` id — so adding a future
 * module only ever means appending one entry here, never editing a nested
 * array or a layout component. `buildNavigationTree` (see
 * `build-navigation-tree.ts`) assembles the flat list into the nested
 * `children` structure the Sidebar actually renders.
 *
 * `titleKey`/`subtitleKey` are i18n message keys (see `src/i18n`), resolved
 * at render time via `useLocale().t()` — never literal display text, since
 * Arabic is the default locale and English is a future secondary one.
 *
 * Sidebar is organized by business ownership (Sales, Shipping, Purchasing,
 * Products & Warehouses, Finance, Data Management), not by database/master-
 * data classification. Shipping Statuses / Methods / Companies live under
 * Shipping — never under Products or generic Basic Data. Customer Groups
 * stay under Sales (distinct from Customers); Supplier Groups stay under
 * Purchasing (distinct from Suppliers). The Products parent has no
 * permission gate so inventory-only users still see movements/stock/count
 * without being granted `products.view`. Identity & Permissions no longer
 * exists as a top-level module.
 * TASK-060 — Roles/RBAC no longer exists (permissions are granted directly
 * per-user from the User Editor); `settings-roles`/`settings-permissions`
 * were removed accordingly, no standalone Permissions page.
 *
 * Routes with no page built yet will 404 until their business pages ship in
 * a later phase — that is expected, not a bug.
 */
export const navigationConfig: NavigationItem[] = [
  {
    id: "dashboard",
    titleKey: "nav.dashboard",
    subtitleKey: "nav.dashboardSubtitle",
    icon: "dashboard",
    route: "/",
    order: 0,
  },

  { id: "crm", titleKey: "nav.crm", icon: "users", order: 10, permissions: ["crm.view"] },
  {
    id: "crm-leads",
    titleKey: "nav.crmLeads",
    parent: "crm",
    route: "/crm/leads",
    icon: "contact",
    order: 0,
    permissions: ["crm.leads.view"],
  },
  {
    id: "crm-funnel",
    titleKey: "workflow.funnel.title",
    parent: "crm",
    route: "/crm/funnel",
    icon: "bar-chart",
    order: 1,
    permissions: ["crm.leads.view"],
  },
  {
    id: "crm-sales-teams",
    titleKey: "nav.crmSalesTeams",
    parent: "crm",
    route: "/crm/sales-teams",
    icon: "users",
    order: 2,
    permissions: ["crm.sales-teams.view"],
  },

  {
    id: "sales",
    titleKey: "nav.sales",
    icon: "shopping-cart",
    order: 20,
    permissions: ["sales.view"],
  },
  {
    id: "sales-customers",
    titleKey: "nav.salesCustomers",
    parent: "sales",
    route: "/sales/customers",
    icon: "contact",
    order: 0,
    permissions: ["partners.view"],
  },
  {
    id: "master-data-customer-groups",
    titleKey: "masterData.customerGroups.title",
    parent: "sales",
    route: "/master-data/customer-groups",
    icon: "users-round",
    order: 1,
    permissions: ["masterdata.customer-groups.view"],
  },
  {
    id: "sales-quotations",
    titleKey: "nav.salesQuotations",
    parent: "sales",
    route: "/sales/quotations",
    icon: "file-text",
    order: 2,
    permissions: ["sales.quotations.view"],
  },
  {
    id: "sales-orders",
    titleKey: "nav.salesOrders",
    parent: "sales",
    route: "/sales/orders",
    icon: "shopping-cart",
    order: 3,
    permissions: ["sales.orders.view"],
  },
  {
    id: "store-orders-list",
    titleKey: "nav.storeOrdersList",
    parent: "sales",
    route: "/store-orders",
    icon: "store",
    order: 4,
    permissions: ["store-orders.view"],
  },
  {
    id: "store-orders-import",
    titleKey: "nav.storeOrdersImport",
    parent: "sales",
    route: "/store-orders/import",
    icon: "upload-cloud",
    order: 5,
    permissions: ["store-orders.view"],
  },
  {
    id: "store-orders-needs-review",
    titleKey: "nav.storeOrdersNeedsReview",
    parent: "sales",
    route: "/store-orders/needs-review",
    icon: "list-checks",
    order: 6,
    permissions: ["store-orders.view"],
  },
  {
    id: "sales-invoices",
    titleKey: "nav.salesInvoices",
    parent: "sales",
    route: "/sales/invoices",
    icon: "receipt",
    order: 7,
    permissions: ["sales.invoices.view"],
  },
  {
    id: "sales-returns",
    titleKey: "nav.salesReturns",
    parent: "sales",
    route: "/sales/returns",
    icon: "undo-2",
    order: 8,
    permissions: ["sales.returns.view"],
  },
  /// Dedicated Shipping module — operational desk plus the shipping master
  /// data that belongs to it (statuses, methods, companies). Those screens
  /// must not appear under Products or Basic Data.
  {
    id: "shipping",
    titleKey: "nav.shipping",
    icon: "ship",
    order: 25,
    permissions: ["shipping.view"],
  },
  {
    id: "store-orders-shipping",
    titleKey: "nav.storeOrdersShipping",
    parent: "shipping",
    route: "/shipping",
    icon: "ship",
    order: 0,
    permissions: ["shipping.view"],
  },
  {
    id: "store-orders-shipping-import",
    titleKey: "nav.storeOrdersShippingImport",
    parent: "shipping",
    route: "/shipping/import",
    icon: "upload-cloud",
    order: 1,
    permissions: ["shipping.view"],
  },
  {
    id: "master-data-shipping-statuses",
    titleKey: "masterData.shippingStatuses.title",
    parent: "shipping",
    route: "/master-data/shipping-statuses",
    icon: "list-checks",
    order: 2,
    permissions: ["masterdata.shipping-statuses.view"],
  },
  {
    id: "master-data-workflow-statuses",
    titleKey: "masterData.workflowStatuses.title",
    parent: "master-data",
    route: "/master-data/workflow-statuses",
    icon: "list-checks",
    order: 25,
    permissions: ["masterdata.view"],
  },
  {
    id: "master-data-workflow-transitions",
    titleKey: "workflow.transitions.title",
    shortTitleKey: "sidebar.short.transitions",
    parent: "master-data",
    route: "/master-data/workflow-transitions",
    icon: "git-branch",
    order: 26,
    permissions: ["masterdata.workflow-transitions.view"],
  },
  {
    id: "master-data-shipping-companies",
    titleKey: "masterData.shippingCompanies.title",
    parent: "shipping",
    route: "/master-data/shipping-companies",
    icon: "truck",
    order: 3,
    permissions: ["masterdata.shipping-companies.view"],
  },

  {
    id: "purchasing",
    titleKey: "nav.purchasing",
    icon: "shopping-bag",
    order: 30,
    permissions: ["purchasing.view"],
  },
  {
    id: "purchasing-suppliers",
    titleKey: "nav.purchasingSuppliers",
    parent: "purchasing",
    route: "/purchasing/suppliers",
    icon: "truck",
    order: 0,
    permissions: ["partners.view"],
  },
  {
    id: "master-data-supplier-groups",
    titleKey: "masterData.supplierGroups.title",
    parent: "purchasing",
    route: "/master-data/supplier-groups",
    icon: "users-round",
    order: 1,
    permissions: ["masterdata.supplier-groups.view"],
  },
  {
    id: "purchasing-quotations",
    titleKey: "nav.purchasingQuotations",
    parent: "purchasing",
    route: "/purchasing/purchase-quotations",
    icon: "file-text",
    order: 2,
    permissions: ["purchasing.quotations.view"],
  },
  {
    id: "purchasing-orders",
    titleKey: "nav.purchasingOrders",
    parent: "purchasing",
    route: "/purchasing/purchase-orders",
    icon: "clipboard-list",
    order: 3,
    permissions: ["purchasing.orders.view"],
  },
  {
    id: "purchasing-invoices",
    titleKey: "nav.purchasingInvoices",
    parent: "purchasing",
    route: "/purchasing/purchase-invoices",
    icon: "receipt",
    order: 4,
    permissions: ["purchasing.invoices.view"],
  },
  {
    id: "purchasing-returns",
    titleKey: "nav.purchasingReturns",
    parent: "purchasing",
    route: "/purchasing/purchase-returns",
    icon: "undo-2",
    order: 5,
    permissions: ["purchasing.returns.view"],
  },
  {
    id: "purchasing-landed-cost",
    titleKey: "nav.purchasingLandedCost",
    parent: "purchasing",
    route: "/purchasing/landed-cost",
    icon: "ship",
    order: 6,
    permissions: ["landed-cost.view"],
  },
  {
    id: "products",
    titleKey: "nav.products",
    shortTitleKey: "sidebar.short.products",
    icon: "package",
    order: 40,
  },
  {
    id: "products-list",
    titleKey: "nav.productsList",
    parent: "products",
    route: "/products",
    icon: "package",
    order: 0,
    permissions: ["products.view"],
  },
  {
    id: "master-data-warehouses",
    titleKey: "masterData.warehouses.title",
    parent: "products",
    route: "/master-data/warehouses",
    icon: "warehouse",
    order: 1,
    permissions: ["masterdata.warehouses.view"],
  },
  {
    id: "master-data-warehouse-locations",
    titleKey: "masterData.warehouseLocations.title",
    parent: "products",
    route: "/master-data/warehouse-locations",
    icon: "map-pin",
    order: 2,
    permissions: ["masterdata.warehouse-locations.view"],
  },
  {
    id: "master-data-units",
    titleKey: "masterData.units.title",
    parent: "products",
    route: "/master-data/units",
    icon: "ruler",
    order: 3,
    permissions: ["masterdata.units.view"],
  },
  {
    id: "master-data-unit-conversions",
    titleKey: "masterData.unitConversions.title",
    parent: "products",
    route: "/master-data/unit-conversions",
    icon: "arrow-left-right",
    order: 4,
    permissions: ["masterdata.units.view"],
  },
  {
    id: "master-data-categories",
    titleKey: "masterData.categories.title",
    parent: "products",
    route: "/master-data/categories",
    icon: "tags",
    order: 5,
    permissions: ["masterdata.categories.view"],
  },
  {
    id: "master-data-brands",
    titleKey: "masterData.brands.title",
    parent: "products",
    route: "/master-data/brands",
    icon: "award",
    order: 6,
    permissions: ["masterdata.brands.view"],
  },
  {
    id: "inventory-movements",
    titleKey: "nav.inventoryMovements",
    parent: "products",
    route: "/inventory/movements",
    icon: "arrow-left-right",
    order: 7,
    permissions: ["inventory.view"],
  },
  {
    id: "inventory-stock",
    titleKey: "nav.inventoryStock",
    parent: "products",
    route: "/inventory/stock",
    icon: "layers",
    order: 8,
    permissions: ["inventory.view"],
  },
  {
    id: "inventory-physical-count",
    titleKey: "nav.inventoryPhysicalCount",
    parent: "products",
    route: "/inventory/physical-count",
    icon: "clipboard-list",
    order: 9,
    permissions: ["inventory.view"],
  },

  {
    id: "hr",
    titleKey: "nav.hr",
    icon: "users",
    order: 50,
    permissions: ["hr.view"],
  },
  {
    id: "hr-my-profile",
    titleKey: "nav.hrMyProfile",
    parent: "hr",
    route: "/hr/my-profile",
    icon: "user-circle",
    order: -1,
  },
  {
    id: "hr-employees",
    titleKey: "nav.hrEmployees",
    parent: "hr",
    route: "/hr/employees",
    icon: "contact",
    order: 0,
    permissions: ["hr.employees.view"],
  },
  {
    id: "hr-kpi-templates",
    titleKey: "nav.hrKpiTemplates",
    parent: "hr",
    route: "/hr/kpi-templates",
    icon: "target",
    order: 1,
    permissions: ["hr.kpi-templates.view"],
  },
  {
    id: "hr-kpi-evaluations",
    titleKey: "nav.hrKpiEvaluations",
    parent: "hr",
    route: "/hr/kpi-evaluations",
    icon: "bar-chart",
    order: 2,
    permissions: ["hr.kpi-evaluations.view"],
  },
  {
    id: "hr-sales-targets",
    titleKey: "nav.hrSalesTargets",
    parent: "hr",
    route: "/hr/sales-targets",
    icon: "target",
    order: 3,
    permissions: ["hr.sales-targets.view"],
  },
  {
    id: "hr-ranking",
    titleKey: "nav.hrRanking",
    parent: "hr",
    route: "/hr/ranking",
    icon: "bar-chart",
    order: 4,
    permissions: ["hr.sales-targets.view"],
  },
  {
    id: "hr-commission-plans",
    titleKey: "nav.hrCommissionPlans",
    parent: "hr",
    route: "/hr/commission-plans",
    icon: "percent",
    order: 5,
    permissions: ["hr.commission-plans.view"],
  },
  {
    id: "hr-commissions",
    titleKey: "nav.hrCommissions",
    parent: "hr",
    route: "/hr/commissions",
    icon: "percent",
    order: 6,
    permissions: ["hr.commissions.view"],
  },
  {
    id: "hr-payroll",
    titleKey: "nav.hrPayroll",
    parent: "hr",
    route: "/hr/payroll",
    icon: "banknote",
    order: 7,
    permissions: ["hr.payroll.view"],
  },
  {
    id: "hr-payroll-components",
    titleKey: "nav.hrPayrollComponents",
    parent: "hr",
    route: "/hr/payroll-components",
    icon: "calculator",
    order: 8,
    permissions: ["hr.payroll-components.view"],
  },

  {
    id: "investors",
    titleKey: "nav.investors",
    icon: "trending-up",
    order: 55,
    permissions: ["investors.view"],
  },
  {
    id: "investors-dashboard",
    titleKey: "nav.investorsDashboard",
    parent: "investors",
    route: "/investors",
    icon: "dashboard",
    order: 0,
    permissions: ["investors.view"],
  },
  {
    id: "investors-list",
    titleKey: "nav.investorsList",
    parent: "investors",
    route: "/investors/list",
    icon: "users",
    order: 1,
    permissions: ["investors.view"],
  },
  {
    id: "investors-opportunities",
    titleKey: "nav.investorsOpportunities",
    parent: "investors",
    route: "/investors/opportunities",
    icon: "briefcase",
    order: 2,
    permissions: ["investment-opportunities.view"],
  },
  {
    id: "investors-settings",
    titleKey: "nav.investorsSettings",
    parent: "investors",
    route: "/investors/settings/investor-types",
    icon: "settings",
    order: 3,
    permissions: ["investor-settings.view"],
  },

  // Agents / Fulfillment Partners (specs/agents-fulfillment-partners) — the
  // INTERNAL management screens. The agent portal (audience "agent") is a
  // separate set of entries.
  {
    id: "agents",
    titleKey: "agents.nav.section",
    icon: "handshake",
    order: 57,
    permissions: ["agents.view"],
  },
  {
    id: "agents-list",
    titleKey: "agents.nav.list",
    parent: "agents",
    route: "/agents",
    icon: "handshake",
    order: 0,
    permissions: ["agents.view"],
  },
  {
    id: "agents-collections",
    titleKey: "agents.nav.collections",
    parent: "agents",
    route: "/agents/collections",
    icon: "hand-coins",
    order: 1,
    permissions: ["agents.finance.view"],
  },

  {
    id: "expenses",
    titleKey: "nav.expenses",
    icon: "calculator",
    order: 60,
    permissions: ["expenses.view"],
  },
  {
    id: "expenses-components",
    titleKey: "nav.expensesComponents",
    parent: "expenses",
    route: "/expenses/cost-components",
    icon: "calculator",
    order: 0,
    permissions: ["masterdata.cost-components.view"],
  },
  {
    id: "expenses-product-cost",
    titleKey: "nav.expensesProductCost",
    parent: "expenses",
    route: "/expenses/product-cost",
    icon: "file-text",
    order: 1,
    permissions: ["expenses.view"],
  },
  {
    id: "expenses-cost-explorer",
    titleKey: "nav.expensesCostExplorer",
    parent: "expenses",
    route: "/expenses/cost-explorer",
    icon: "layers",
    order: 2,
    permissions: ["cost-explorer.view"],
  },

  {
    id: "finance",
    titleKey: "nav.finance",
    icon: "landmark",
    order: 70,
    permissions: ["finance.view"],
  },
  {
    id: "finance-receiving-accounts",
    titleKey: "nav.financeReceivingAccounts",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/receiving-accounts",
    icon: "landmark",
    order: 0,
  },
  {
    id: "finance-journal-entries",
    titleKey: "nav.financeJournalEntries",
    parent: "finance",
    group: "finance-ledger",
    route: "/finance/journal-entries",
    icon: "book-text",
    order: 1,
    permissions: ["accounting.journal-entries.view"],
  },
  /// The General Ledger is one report of the Finance reports page — linked
  /// here (next to Journal Entries) so accountants find it where they work.
  {
    id: "finance-general-ledger",
    titleKey: "reports.finance.generalLedger",
    parent: "finance",
    group: "finance-ledger",
    route: "/reports/finance?report=generalLedger",
    icon: "library",
    order: 1.5,
    permissions: ["reports.financial.view"],
  },
  {
    id: "finance-chart-of-accounts",
    titleKey: "nav.financeChartOfAccounts",
    parent: "finance",
    group: "finance-ledger",
    route: "/finance/chart-of-accounts",
    icon: "file-text",
    order: 2,
    permissions: ["accounting.chart-of-accounts.view"],
  },
  {
    id: "finance-cost-centers",
    titleKey: "nav.financeCostCenters",
    parent: "finance",
    group: "finance-assets",
    route: "/finance/cost-centers",
    icon: "target",
    order: 3,
  },
  {
    id: "master-data-analytic-accounts",
    titleKey: "masterData.analyticAccounts.title",
    parent: "finance",
    group: "finance-assets",
    route: "/master-data/analytic-accounts",
    icon: "git-branch",
    order: 4,
  },
  {
    id: "master-data-analytic-plans",
    titleKey: "masterData.analyticPlans.title",
    parent: "finance",
    group: "finance-assets",
    route: "/master-data/analytic-plans",
    icon: "folder-kanban",
    order: 5,
  },
  {
    id: "master-data-payment-methods",
    titleKey: "masterData.paymentMethods.title",
    parent: "finance",
    group: "finance-setup",
    route: "/master-data/payment-methods",
    icon: "banknote",
    order: 6,
  },
  {
    id: "master-data-payment-terms",
    titleKey: "masterData.paymentTerms.title",
    parent: "finance",
    group: "finance-setup",
    route: "/master-data/payment-terms",
    icon: "calendar-clock",
    order: 7,
  },
  {
    id: "finance-expenses",
    titleKey: "nav.financeExpenses",
    parent: "finance",
    group: "finance-operations",
    route: "/finance/expenses",
    icon: "receipt",
    order: 8,
  },
  {
    id: "finance-customer-receipts",
    titleKey: "nav.financeCustomerReceipts",
    parent: "finance",
    group: "finance-operations",
    route: "/sales/payments",
    icon: "banknote",
    order: 9,
    permissions: ["sales.receipts.view"],
  },
  {
    id: "finance-supplier-payments",
    titleKey: "nav.financeSupplierPayments",
    parent: "finance",
    group: "finance-operations",
    route: "/purchasing/payments",
    icon: "wallet",
    order: 10,
    permissions: ["purchasing.payments.view"],
  },
  {
    id: "finance-payment-review",
    titleKey: "nav.financePaymentReview",
    parent: "finance",
    group: "finance-operations",
    route: "/finance/payment-review",
    icon: "clipboard-check",
    order: 10.5,
    permissions: ["sales.receipts.view"],
  },
  {
    id: "finance-payment-reconciliation",
    titleKey: "paymentReconciliation.nav.title",
    parent: "finance",
    group: "finance-operations",
    route: "/finance/payment-reconciliation",
    icon: "arrow-left-right",
    order: 10.6,
    permissions: ["finance.payment-reconciliation.view"],
  },
  {
    id: "finance-bank-transactions",
    titleKey: "nav.financeBankTransactions",
    parent: "finance",
    group: "finance-operations",
    route: "/finance/bank-transactions",
    icon: "landmark",
    order: 11,
    permissions: ["accounting.bank-transactions.view"],
  },
  {
    id: "finance-journals",
    titleKey: "nav.financeJournals",
    parent: "finance",
    group: "finance-ledger",
    route: "/finance/journals",
    icon: "library",
    order: 12,
  },
  {
    id: "finance-payment-sources",
    titleKey: "nav.financePaymentSources",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/payment-sources",
    icon: "credit-card",
    order: 13,
    permissions: ["masterdata.payment-sources.view"],
  },
  {
    id: "finance-fulfillment-cost-rules",
    titleKey: "nav.financeFulfillmentCostRules",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/fulfillment-cost-rules",
    icon: "package",
    order: 13.5,
    permissions: ["masterdata.fulfillment-cost-rules.view"],
  },
  {
    id: "finance-carrier-reconciliation",
    titleKey: "nav.financeCarrierReconciliation",
    parent: "finance",
    group: "finance-operations",
    route: "/finance/carrier-reconciliation",
    icon: "truck",
    order: 13.6,
    permissions: ["carrier-reconciliation.view"],
  },
  {
    id: "finance-cost-allocation-rules",
    titleKey: "nav.financeCostAllocationRules",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/cost-allocation-rules",
    icon: "git-branch",
    order: 13.7,
    permissions: ["masterdata.cost-allocation-rules.view"],
  },
  {
    id: "finance-projects",
    titleKey: "nav.financeProjects",
    parent: "finance",
    group: "finance-assets",
    route: "/finance/projects",
    icon: "folder-kanban",
    order: 14,
  },
  {
    id: "finance-fixed-assets",
    titleKey: "nav.financeFixedAssets",
    parent: "finance",
    group: "finance-assets",
    route: "/finance/fixed-assets",
    icon: "building",
    order: 15,
    permissions: ["masterdata.fixed-assets.view"],
  },
  {
    id: "finance-prepaid-expenses",
    titleKey: "nav.financePrepaidExpenses",
    parent: "finance",
    group: "finance-assets",
    route: "/finance/prepaid-expenses",
    icon: "calendar-clock",
    order: 15.2,
    permissions: ["prepaid-expenses.view"],
  },
  {
    id: "finance-accrued-expenses",
    titleKey: "nav.financeAccruedExpenses",
    parent: "finance",
    group: "finance-assets",
    route: "/finance/accrued-expenses",
    icon: "wallet",
    order: 15.4,
    permissions: ["accrued-expenses.view"],
  },
  {
    id: "finance-fx",
    titleKey: "nav.financeFx",
    parent: "finance",
    group: "finance-ledger",
    route: "/finance/exchange-rates",
    icon: "coins",
    order: 15.6,
    permissions: ["exchange-rates.view"],
  },
  {
    id: "finance-fiscal-periods",
    titleKey: "nav.financeFiscalPeriods",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/fiscal-periods",
    icon: "calendar-clock",
    order: 16,
  },
  {
    id: "finance-opening-balances",
    titleKey: "nav.financeOpeningBalances",
    parent: "finance",
    group: "finance-ledger",
    route: "/finance/opening-balances",
    icon: "wallet",
    order: 17,
    permissions: ["accounting.opening-balances.view"],
  },
  {
    id: "finance-year-closing",
    titleKey: "nav.financeYearClosing",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/year-closing",
    icon: "calendar-check",
    order: 18,
  },
  {
    id: "finance-accounting-settings",
    titleKey: "nav.financeAccountingSettings",
    parent: "finance",
    group: "finance-setup",
    route: "/finance/accounting-settings",
    icon: "sliders",
    order: 19,
  },
  {
    id: "master-data-currencies",
    titleKey: "masterData.currencies.title",
    parent: "finance",
    group: "finance-setup",
    route: "/master-data/currencies",
    icon: "coins",
    order: 20,
  },
  {
    id: "master-data-taxes",
    titleKey: "masterData.taxes.title",
    parent: "finance",
    group: "finance-setup",
    route: "/master-data/taxes",
    icon: "percent",
    order: 21,
  },

  /// Standalone top-level module (Enterprise Import Center) — a single
  /// centralized entry point for Excel/CSV/Google Sheets imports across
  /// every module, deliberately not nested under Finance since it also
  /// covers Sales/Purchasing/Inventory/CRM data.
  {
    id: "data-management",
    titleKey: "nav.dataManagement",
    icon: "layers",
    order: 85,
    permissions: ["datamanagement.view"],
  },
  {
    id: "data-management-import-center",
    titleKey: "nav.dataManagementImportCenter",
    parent: "data-management",
    route: "/data-management/import-center",
    icon: "upload-cloud",
    order: 0,
    permissions: ["import-center.view"],
  },

  /// Cross-cutting geographic/language reference data that does not belong
  /// to a single operational module. Domain master data (warehouses,
  /// payment methods, customer groups, …) lives under its owning section.
  {
    id: "master-data",
    titleKey: "nav.masterData",
    icon: "database",
    order: 80,
    permissions: ["masterdata.view"],
  },
  {
    id: "master-data-countries",
    titleKey: "masterData.countries.title",
    parent: "master-data",
    route: "/master-data/countries",
    icon: "globe",
    order: 0,
  },
  {
    id: "master-data-cities",
    titleKey: "masterData.cities.title",
    parent: "master-data",
    route: "/master-data/cities",
    icon: "map-pin",
    order: 1,
  },
  {
    id: "master-data-languages",
    titleKey: "masterData.languages.title",
    parent: "master-data",
    route: "/master-data/languages",
    icon: "languages",
    order: 2,
  },
  {
    id: "master-data-transaction-types",
    titleKey: "masterData.transactionTypes.title",
    parent: "master-data",
    route: "/master-data/transaction-types",
    icon: "arrow-left-right",
    order: 3,
  },

  /// Core module (must always exist) — shell only, no report is generated
  /// yet (TASK-024 Part 5). Categories are direct children, same shape as
  /// Master Data above.
  {
    id: "reports",
    titleKey: "nav.reports",
    icon: "bar-chart",
    order: 90,
    permissions: ["reports.view"],
  },
  {
    id: "reports-executive",
    titleKey: "nav.reportsExecutive",
    parent: "reports",
    route: "/reports/executive",
    icon: "bar-chart",
    order: 0,
  },
  {
    id: "reports-sales",
    titleKey: "nav.reportsSales",
    parent: "reports",
    route: "/reports/sales",
    icon: "shopping-cart",
    order: 1,
  },
  {
    id: "reports-crm",
    titleKey: "nav.reportsCrm",
    parent: "reports",
    route: "/reports/crm",
    icon: "contact",
    order: 2,
  },
  {
    id: "reports-purchasing",
    titleKey: "nav.reportsPurchasing",
    parent: "reports",
    route: "/reports/purchasing",
    icon: "shopping-bag",
    order: 3,
  },
  {
    id: "reports-inventory",
    titleKey: "nav.reportsInventory",
    parent: "reports",
    route: "/reports/inventory",
    icon: "boxes",
    order: 4,
    permissions: ["reports.inventory.view"],
  },
  {
    id: "reports-finance",
    titleKey: "nav.reportsFinance",
    parent: "reports",
    route: "/reports/finance",
    icon: "landmark",
    order: 5,
    permissions: ["reports.financial.view"],
  },
  {
    id: "reports-expenses",
    titleKey: "nav.reportsExpenses",
    parent: "reports",
    route: "/reports/expenses",
    icon: "calculator",
    order: 6,
  },
  {
    id: "reports-customers",
    titleKey: "nav.reportsCustomers",
    parent: "reports",
    route: "/reports/customers",
    icon: "users-round",
    order: 7,
  },
  {
    id: "reports-suppliers",
    titleKey: "nav.reportsSuppliers",
    parent: "reports",
    route: "/reports/suppliers",
    icon: "truck",
    order: 8,
  },
  {
    id: "reports-shipping",
    titleKey: "nav.reportsShipping",
    parent: "reports",
    route: "/reports/shipping",
    icon: "ship",
    order: 9,
  },
  {
    id: "reports-custom",
    titleKey: "nav.reportsCustom",
    parent: "reports",
    route: "/reports/custom",
    icon: "file-text",
    order: 10,
  },
  {
    id: "reports-analytics",
    titleKey: "nav.reportsAnalytics",
    parent: "reports",
    route: "/reports/analytics",
    icon: "layers",
    order: 11,
  },

  /// System configuration ONLY (TASK-024 Part 4) — no master data lives
  /// here. Every child is a shell page: "Prepare pages only."
  {
    id: "settings",
    titleKey: "nav.settings",
    icon: "settings",
    order: 100,
    permissions: ["settings.view"],
  },
  {
    id: "settings-general",
    titleKey: "nav.settingsGeneral",
    parent: "settings",
    route: "/settings/general",
    icon: "sliders",
    order: 0,
  },
  {
    id: "settings-users",
    titleKey: "nav.settingsUsers",
    parent: "settings",
    route: "/settings/users",
    icon: "users",
    order: 1,
    permissions: ["settings.manage"],
  },
  {
    id: "master-data-departments",
    titleKey: "masterData.departments.title",
    parent: "settings",
    route: "/master-data/departments",
    icon: "building",
    order: 2,
    permissions: ["masterdata.departments.view"],
  },
  {
    id: "master-data-job-titles",
    titleKey: "masterData.jobTitles.title",
    parent: "settings",
    route: "/master-data/job-titles",
    icon: "award",
    order: 2.1,
    permissions: ["masterdata.job-titles.view"],
  },
  {
    id: "master-data-customer-classifications",
    titleKey: "masterData.customerClassifications.title",
    parent: "settings",
    route: "/master-data/customer-classifications",
    icon: "tags",
    order: 2.2,
    permissions: ["masterdata.customer-classifications.view"],
  },
  {
    id: "master-data-no-purchase-reasons",
    titleKey: "masterData.noPurchaseReasons.title",
    parent: "settings",
    route: "/master-data/no-purchase-reasons",
    icon: "clipboard-list",
    order: 2.4,
    permissions: ["masterdata.no-purchase-reasons.view"],
  },
  {
    id: "master-data-lead-follow-up-types",
    titleKey: "masterData.leadFollowUpTypes.title",
    parent: "settings",
    route: "/master-data/lead-follow-up-types",
    icon: "calendar-clock",
    order: 2.5,
    permissions: ["masterdata.lead-follow-up-types.view"],
  },
  {
    id: "settings-document-numbering",
    titleKey: "nav.settingsDocumentNumbering",
    parent: "settings",
    route: "/settings/document-numbering",
    icon: "hash",
    order: 4,
  },
  {
    id: "settings-print-settings",
    titleKey: "nav.settingsPrintSettings",
    parent: "settings",
    route: "/settings/print-settings",
    icon: "printer",
    order: 5,
  },
  {
    id: "settings-notifications",
    titleKey: "nav.settingsNotifications",
    parent: "settings",
    route: "/settings/notifications",
    icon: "bell",
    order: 6,
  },
  {
    id: "settings-integrations",
    titleKey: "nav.settingsIntegrations",
    parent: "settings",
    route: "/settings/integrations",
    icon: "plug",
    order: 7,
  },
  {
    id: "settings-security",
    titleKey: "nav.settingsSecurity",
    parent: "settings",
    route: "/settings/security",
    icon: "shield",
    order: 8,
  },
  {
    id: "settings-backup",
    titleKey: "nav.settingsBackup",
    parent: "settings",
    route: "/settings/backup",
    icon: "hard-drive",
    order: 9,
  },

  // External agent portal (specs/agents-fulfillment-partners §10) — audience
  // "agent": shown only to AGENT users, never to internal staff. Each entry
  // gates on the `agent.*` permission its page's API requires.
  {
    id: "agent-portal-dashboard",
    titleKey: "agentPortal.nav.dashboard",
    icon: "dashboard",
    route: "/agent",
    order: 0,
    audience: "agent",
    permissions: ["agent.dashboard.view"],
  },
  {
    id: "agent-portal-leads",
    titleKey: "agentPortal.nav.leads",
    icon: "contact",
    route: "/agent/leads",
    order: 1,
    audience: "agent",
    permissions: ["agent.leads.view"],
  },
  {
    id: "agent-portal-orders",
    titleKey: "agentPortal.nav.orders",
    icon: "shopping-cart",
    route: "/agent/orders",
    order: 2,
    audience: "agent",
    permissions: ["agent.orders.view"],
  },
  {
    id: "agent-portal-stock",
    titleKey: "agentPortal.nav.stock",
    icon: "boxes",
    route: "/agent/stock",
    order: 3,
    audience: "agent",
    permissions: ["agent.stock.view"],
  },
  {
    id: "agent-portal-statement",
    titleKey: "agentPortal.nav.statement",
    icon: "book-text",
    route: "/agent/statement",
    order: 4,
    audience: "agent",
    permissions: ["agent.statement.view"],
  },
  {
    id: "agent-portal-payouts",
    titleKey: "agentPortal.nav.payouts",
    icon: "hand-coins",
    route: "/agent/payouts",
    order: 5,
    audience: "agent",
    permissions: ["agent.payouts.view"],
  },
  {
    id: "agent-portal-team",
    titleKey: "agentPortal.nav.team",
    icon: "users-round",
    route: "/agent/team",
    order: 6,
    audience: "agent",
    permissions: ["agent.team.view"],
  },
];
