import { Injectable } from '@nestjs/common';
import { Prisma, ProductSupplyMethod } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { InventoryValuationService } from '../../accounting/inventory-valuation/inventory-valuation.service';
import { RecipeService, type LoadedRecipe } from '../../recipes/recipe.service';
import { ownerViolation } from '../../recipes/recipe-rules';
import { notFound, unprocessable } from '../../common/errors/business-errors';

type Client = Prisma.TransactionClient | PrismaService;

/** Whether a product moves stock: a tracked item, or a kit (fulfilled from its components). */
export function isStockAffecting(product: {
  isInventoryItem: boolean;
  supplyMethod: ProductSupplyMethod;
}): boolean {
  return product.isInventoryItem || product.supplyMethod === 'KIT';
}

export interface StockLineInput {
  productId: string;
  quantity: number;
  warehouseId: string;
  /** Caller's key of the document line — every stock line (and snapshot) of that line carries it. */
  lineKey: string;
}

export interface ResolvedStockLine {
  productId: string;
  quantity: number;
  warehouseId: string;
  lineKey: string;
  /** Set on component lines generated by a kit line: the kit that was sold. */
  parentProductId?: string;
  recipeId?: string;
  recipeVersion?: number;
}

export interface KitSnapshot {
  recipeId: string;
  version: number;
  components: {
    productId: string;
    qtyPerKit: number;
    /** Moving-average cost at resolution time — the cost the COGS is booked at. */
    unitCost: string;
  }[];
}

export interface ResolvedStockLines {
  stock: ResolvedStockLine[];
  kitSnapshots: Record<string, KitSnapshot>;
}

/**
 * Turns document lines (sales invoice, store order, agent dispatch, returns…)
 * into the stock lines they actually move (R13 spec §3, api-contract §3):
 *  - a tracked product passes through unchanged;
 *  - a KIT line expands into its components from the ACTIVE recipe
 *    (`qtyPerKit × quantity`, whole numbers), stamped with the kit and recipe so
 *    the movements stay traceable, and a snapshot of the recipe + component
 *    costs is returned for the document line (COGS is the sum of component costs);
 *  - a service / non-stock product moves nothing and is dropped.
 * A kit with no active recipe, or with components of another owner than the kit,
 * is rejected (422) — never silently delivered from the wrong stock.
 */
@Injectable()
export class StockLineResolver {
  constructor(
    private readonly prisma: PrismaService,
    private readonly recipes: RecipeService,
    private readonly valuation: InventoryValuationService,
  ) {}

  async resolve(
    tx: Client,
    lines: StockLineInput[],
  ): Promise<ResolvedStockLines> {
    for (const line of lines) {
      if (!Number.isInteger(line.quantity) || line.quantity <= 0) {
        throw unprocessable(
          'STOCK_LINE_QUANTITY_INVALID',
          'A stock line needs a positive whole quantity.',
          { lineKey: line.lineKey },
        );
      }
    }
    const products = await tx.product.findMany({
      where: { id: { in: [...new Set(lines.map((line) => line.productId))] } },
      select: {
        id: true,
        sku: true,
        name: true,
        isInventoryItem: true,
        supplyMethod: true,
      },
    });
    const byId = new Map(products.map((product) => [product.id, product]));

    const stock: ResolvedStockLine[] = [];
    const kitSnapshots: Record<string, KitSnapshot> = {};
    const kitCache = new Map<string, Promise<KitSnapshot>>();

    for (const line of lines) {
      const product = byId.get(line.productId);
      if (!product) {
        throw notFound('PRODUCT_NOT_FOUND', 'The product does not exist.', {
          productId: line.productId,
        });
      }
      if (!isStockAffecting(product)) continue;

      if (product.supplyMethod !== ProductSupplyMethod.KIT) {
        stock.push({
          productId: line.productId,
          quantity: line.quantity,
          warehouseId: line.warehouseId,
          lineKey: line.lineKey,
        });
        continue;
      }

      let resolved = kitCache.get(product.id);
      if (!resolved) {
        resolved = this.resolveKit(tx, product);
        kitCache.set(product.id, resolved);
      }
      const kit = await resolved;
      kitSnapshots[line.lineKey] = kit;
      for (const component of kit.components) {
        stock.push({
          productId: component.productId,
          quantity: component.qtyPerKit * line.quantity,
          warehouseId: line.warehouseId,
          lineKey: line.lineKey,
          parentProductId: product.id,
          recipeId: kit.recipeId,
          recipeVersion: kit.version,
        });
      }
    }
    return { stock, kitSnapshots };
  }

  private async resolveKit(
    tx: Client,
    product: { id: string; sku: string; name: string },
  ): Promise<KitSnapshot> {
    const recipe = await this.recipes.getActiveRecipe(tx, product.id);
    if (!recipe) {
      throw unprocessable(
        'KIT_NO_ACTIVE_RECIPE',
        `Kit ${product.sku} ${product.name} has no active recipe — activate one before selling it.`,
        { productId: product.id },
      );
    }
    this.assertSingleOwner(recipe);
    const perKit = await this.recipes.resolveStockQuantities(tx, recipe, 1);
    const components: KitSnapshot['components'] = [];
    for (const line of perKit) {
      components.push({
        productId: line.componentProductId,
        qtyPerKit: line.quantity,
        unitCost: (
          await this.valuation.getUnitCostDecimal(line.componentProductId, tx)
        ).toString(),
      });
    }
    return { recipeId: recipe.id, version: recipe.version, components };
  }

  /** Mixed company / agent / multi-agent combinations are blocked at transaction time too (a component's owner may have changed since activation). */
  private assertSingleOwner(recipe: LoadedRecipe) {
    const label = (item: { sku: string; name: string }) =>
      `${item.sku} ${item.name}`;
    const message = ownerViolation(
      {
        id: recipe.product.id,
        label: label(recipe.product),
        ownerAgentId: recipe.product.ownerAgentId,
      },
      recipe.lines.map((line) => ({
        id: line.componentProduct.id,
        label: label(line.componentProduct),
        ownerAgentId: line.componentProduct.ownerAgentId,
      })),
    );
    if (message) throw unprocessable('KIT_OWNER_MIXED', message);
  }
}
