-- Sequence backing Lead.leadNumber ("LD-000001", ...). Generated by the
-- application (LeadsService), not a Prisma-managed default, so it isn't
-- declared in schema.prisma.
CREATE SEQUENCE IF NOT EXISTS lead_number_seq;
