import { z } from "zod";

export const productSchema = z.object({
  name: z.string().min(1),
  nameEn: z.string().optional().or(z.literal("")),
  internalName: z.string().min(1),
  displayName: z.string().min(1),
  barcode: z.string().optional().or(z.literal("")),
  qrCodeValue: z.string().optional().or(z.literal("")),
  imageUrl: z.string().optional().or(z.literal("")),
  description: z.string().optional().or(z.literal("")),
  shortDescription: z.string().optional().or(z.literal("")),
  longDescription: z.string().optional().or(z.literal("")),
  internalNotes: z.string().optional().or(z.literal("")),
  tagsInput: z.string().optional().or(z.literal("")),

  type: z.enum([
    "PURCHASE_ONLY",
    "SALES_ONLY",
    "PURCHASE_AND_SALE",
    "MANUFACTURED",
    "SERVICE",
    "EXPENSE_ITEM",
  ]),
  status: z.enum(["ACTIVE", "INACTIVE"]),
  categoryId: z.string().min(1),
  brandId: z.string().optional().or(z.literal("")),
  unitId: z.string().min(1),
  taxId: z.string().optional().or(z.literal("")),
  analyticAccountId: z.string().optional().or(z.literal("")),

  salesPrice: z.number().optional(),
  salesTaxIncluded: z.boolean(),
  salesDescription: z.string().optional().or(z.literal("")),
  allowDiscount: z.boolean(),
  isSellable: z.boolean(),

  purchasePrice: z.number().optional(),
  preferredSupplierId: z.string().optional().or(z.literal("")),
  purchaseDescription: z.string().optional().or(z.literal("")),
  isPurchasable: z.boolean(),

  isInventoryItem: z.boolean(),
  reorderLevel: z.number().optional(),
  reorderQuantity: z.number().optional(),
  safetyStock: z.number().optional(),
  minQuantity: z.number().optional(),
  maxQuantity: z.number().optional(),
  storageLocation: z.string().optional().or(z.literal("")),
  preferredWarehouseId: z.string().optional().or(z.literal("")),
  costingMethod: z.enum(["AVERAGE", "FIFO", "STANDARD"]).optional().or(z.literal("")),
  /**
   * Single-select the form works with (TASK-028 Part 2) — the API still
   * stores `serialNumberTracking`/`batchTracking` as two booleans (ADR-0012),
   * so this is converted to/from that pair at the form's edges
   * (`toProductFormValues` / submit payload in product-modal.tsx), never
   * carried as a third, parallel field.
   */
  inventoryTracking: z.enum(["NONE", "BATCH", "SERIAL"]),
  weight: z.number().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  length: z.number().optional(),
});

export type ProductFormValues = z.infer<typeof productSchema>;

export const productDefaultValues: ProductFormValues = {
  name: "",
  nameEn: "",
  internalName: "",
  displayName: "",
  barcode: "",
  qrCodeValue: "",
  imageUrl: "",
  description: "",
  shortDescription: "",
  longDescription: "",
  internalNotes: "",
  tagsInput: "",
  type: "PURCHASE_AND_SALE",
  status: "ACTIVE",
  categoryId: "",
  brandId: "",
  unitId: "",
  taxId: "",
  analyticAccountId: "",
  salesPrice: undefined,
  salesTaxIncluded: false,
  salesDescription: "",
  allowDiscount: true,
  isSellable: true,
  purchasePrice: undefined,
  preferredSupplierId: "",
  purchaseDescription: "",
  isPurchasable: true,
  isInventoryItem: true,
  reorderLevel: undefined,
  reorderQuantity: undefined,
  safetyStock: undefined,
  minQuantity: undefined,
  maxQuantity: undefined,
  storageLocation: "",
  preferredWarehouseId: "",
  costingMethod: "",
  inventoryTracking: "NONE",
  weight: undefined,
  width: undefined,
  height: undefined,
  length: undefined,
};
