-- Sequence backing Payment.paymentNumber ("PAY-000001", ...). Independent
-- from lead_number_seq / sales_order_number_seq. Generated by the
-- application (PaymentsService), not a Prisma-managed default, so it isn't
-- declared in schema.prisma.
CREATE SEQUENCE IF NOT EXISTS payment_number_seq;
