-- Sequence backing SalesOrder.orderNumber ("SO-000001", ...). Independent
-- from lead_number_seq (decision #12). Generated by the application
-- (SalesOrdersService), not a Prisma-managed default, so it isn't declared
-- in schema.prisma.
CREATE SEQUENCE IF NOT EXISTS sales_order_number_seq;
